### ISSUE TITLE
Problem with php imput (jSON data)

### ISSUE THREAD

**Issue by KilluaKira** [sant0ro/habbo-camera-server#11]
Hi, i have this problem http://prntscr.com/acqwg2

http://www.sunakehotel.com/resources/server-camera/ServerCamera.php

the php input, isn't a valid jSON data!

i changed correctly 

'server-camera' => 'server-camera', // base folder

http://prntscr.com/acqxv3

http://prntscr.com/acqy0o

**Comment by Anthologique** [comment]
I have the same problem...

**Comment by sant0ro** [comment]
Go to hell.

You don't read the documentation and say that exists the problem. Killua already fixed it. After reading the documentation.  GO TO HELL @Anthologique i will not answer your questions anymore.

**Comment by Anthologique** [comment]
Dont work for me :(, help me teamviewer please and i stop my question after...

**Comment by Anthologique** [comment]
I am french and i dont understand why install the camera on my hotel...
Please help me.

**Comment by sant0ro** [comment]
@Anthologique you need understand a simple fact. Read the documentation, Threads at RaGEZONE. I alredy explained how do this many times. See the closed issues.

The Habbo Camera Server isn't accessed by the browser. The Emulator will do requests to the Camera Server. (In the case Yupi Emulator).

You need first extract all the Habbo SWF's assets (figures, furnitures) using Habbo Asset Extractor. (made by me).

What angry me is that some people don't try read before do questions. GitHub issues aren't for these type of questions. Of course you can create issues for that, but many people do that. In big repositories for Games like Citra Emulator, a lot of dummy issues are created. The collaborators often answer. Because is a development repository. Sometimes you need understand that some things aren't made for noobs or newbies. I'm not saying you're dumb. But for some things you need have the minimal or amateur knowledge for do something.

If you read the error you will see 'the input isn't valid json', see what is jSON. You will see that the camera server isn't accessed by an user. The Camera Server exists only for receive jSON requests from the Emulator, and generate the PNG files with the jSON data. And send back to Emulator the Image URL.

Good luck!

**Comment by Anthologique** [comment]
I have found ALL your tutorial and dont work !!!!
Add a tutorial just for Yupi Camera on Ragezone please.
![animation](https://cloud.githubusercontent.com/assets/6734589/15656281/e5550db8-26a5-11e6-9e34-03c6020e17ec.gif)

Please look the screenshot:
