### ISSUE TITLE
Error #500

### ISSUE THREAD

**Issue by DJGOMEZV** [sant0ro/habbo-camera-server#5]
![sin titulo](https://cloud.githubusercontent.com/assets/14180119/9735557/878ac5f4-5605-11e5-9dd9-d4424a92b6d4.png)

Put the URL/ServerCamera.php?Install=true gives me the same error that may be, can you tell me how to fix it?

**Comment by iArjan** [comment]
Run it from localhost

**Comment by sant0ro** [comment]
Run it from Localhost ;)

**Comment by DJGOMEZV** [comment]
And I did nothing.

**Comment by sant0ro** [comment]
Read the installation tutorial in the RageZONE thread. You need run installation in localhost. Or add your IP in white-list. Also, after installation need using Asset Extractor.

**Comment by DJGOMEZV** [comment]
I could already install the script but it gives me error emulator, if I have the beta and running, is complete in stages of the camera?
![nmj8ho3](https://cloud.githubusercontent.com/assets/14180119/10562378/3405129e-7523-11e5-933f-5635d000b936.png)

**Comment by sant0ro** [comment]
Yes, camera is totally working in 2.0
You need configure your extra settings.ini with correct configuration.
And also need to configure your external variables,
also need put crossdomain.xml in your HOST were is the ServerCamera.php
Also need put al assets in the same folder from servercamera.php (respectively sprites,masks) also you need create folders with all country languages, or change in the servercamera.php the Hotel Country to a static hotel country...

Reasons of error:
1. bad url on extrasettings
2. bad path on extrasettings
3. bad url on external variables
4. can't create image because the country folder doesnt exists
5. crossdomain.xml problem
6. assets doesnt exists (but that not generate an error)
7. also need to configure in extrasettings.ini to the thumbnail as servercamera.php?room

**Comment by DJGOMEZV** [comment]
I could already solve that because the camera works for me and all, but when buying furni not leave me with the photo in my inventory as I do to fix that?

**Comment by sant0ro** [comment]
Hi Djgomez, you must check if your SWF has the Furni of Habbo Camera,
Also you need set in Configuration the Furni ID.
You need put in your CATALOG_FURNIS and CATALOG_ITEMS the Camera photo.

Also please tell me, the PREVIEW of the Image works?
When you click buy, the image has an 'slide effect' to inventary yeah?
Only the item is black or doesnt appear yeah?

If yes, it's exactly what i said
You need have the furni from Camera ,  i think is external_wallitem_poster something like that. You can check in Azure Emu source Code the Furni Name, because the Emulator check the existence of that item.

Also you need put in catalog_furnis and catalog_items.

Hope i helped you.
Please use RageZONE help section.

**Comment by DJGOMEZV** [comment]
Where in the emulator revised if the name of furni correct? and Preview image if it looks, but give me not buy the furniture in the camera appears in my inventory.

**Comment by DJGOMEZV** [comment]
the furni this in furnis and catalog_items catalog when I bought the picture tells me that was already sent to the inventory, does the animation and everything to move the box but when I open it there is nothing, no logs the emulator or no errors.
